steps:
 - name: 'gcr.io/cloud-builders/npm'
   args: ['install']
 - name: 'gcr.io/cloud-builders/gcloud'
   args: 
   - kms
   - decrypt
   - --ciphertext-file=.env.enc
   - --plaintext-file=.env
   - --location=global
   - --keyring=keyring1
   - --key=cloudbuild-env
 - name: 'gcr.io/cloud-builders/gsutil'
   args: ['cp', '.env', 'environment.yml']
   id: 'setenv'
 - name: 'gcr.io/cloud-builders/gcloud'
   waitFor: ['setenv']
   args:
   - functions
   - deploy
   - emailSender
   - --runtime=nodejs8
   - --trigger-http
   - --env-vars-file=.example.environment.yml
 - name: 'gcr.io/cloud-builders/gcloud'
   waitFor: ['setenv']
   args:
   - functions
   - deploy
   - http
   - --runtime=nodejs8
   - --trigger-http
   - --env-vars-file=.example.environment.yml
   - emailSender
   - --runtime=nodejs8
   - --trigger-http
   - --env-vars-file=.example.environment.yml
 - name: 'gcr.io/cloud-builders/gcloud'
   waitFor: ['setenv']
   args:
   - functions
   - deploy
   - http
   - --runtime=nodejs8
   - --trigger-http
   - --env-vars-file=example.environment.yml
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - app
   - deploy
   - --no-promote

secrets:
 - kmsKeyName: projects/teak-banner-234513/locations/global/keyRings/keyring1/cryptoKeys/cloudbuild-env
   secretEnv:
    MY_SECRET: CiQAxmBqc33p44QXEmWWPgpAmbW7tL2nqkeeBf81f+BHO3PGy80SIQDuzAMwne89l0GmJDJlKD2M
nGv2+i8m77ilABgVZhmDuw==
    
