steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/${PROJECT_ID}/serverless-image', '.']
 - name: 'gcr.io/cloud-builders/npm'
   args: ['install']
 - name: 'gcr.io/cloud-builders/gcloud'
   args: 
   - kms
   - decrypt
   - --ciphertext-file=.env.enc
   - --plaintext-file=.env
   - --location=global
   - --keyring=keyring1
   - --key=cloudbuild-env
 - name: 'gcr.io/cloud-builders/gsutil'
   args: ['cp', '*', '/workspace/']
 - name: 'gcr.io/cloud-builders/gsutil'
   args: ['cp', '.env', 'environment.yml']
   id: 'setenv'
 - name: 'gcr.io/cloud-builders/gcloud'
   waitFor: ['setenv']
   args:
   - functions
   - deploy
   - emailSender
   - --runtime=nodejs8
   - --trigger-http
   - --env-vars-file=environment.yml
 - name: 'gcr.io/cloud-builders/gcloud'
   waitFor: ['setenv']
   args:
   - functions
   - deploy
   - http
   - --runtime=nodejs8
   - --trigger-http
   - --env-vars-file=environment.yml
 - name: 'gcr.io/cloud-builders/gcloud'
   waitFor: ['setenv']
   args:
   - functions
   - deploy
   - smsSender
   - --runtime=nodejs8
   - --trigger-http
   - --env-vars-file=environment.yml
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - app
   - deploy
   - --no-promote
images: ['gcr.io/${PROJECT_ID}/serverless-image']
