steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/${PROJECT_ID}/serverless-image', '.']
 - name: 'gcr.io/cloud-builders/npm'
   args: ['install']
 - name: 'gcr.io/cloud-builders/npm'
   args: ['install', '-g', 'serverless']
 - name: 'gcr.io/cloud-builders/gcloud'
   args: 
   - kms
   - decrypt
   - --ciphertext-file=.env.enc
   - --plaintext-file=.env
   - --location=global
   - --keyring=keyring1
   - --key=cloudbuild-env
 - name: 'gcr.io/cloud-builders/gsutil'
   args: ['cp', '*', '/workspace/']
 - name: 'gcr.io/cloud-builders/gsutil'
   args: ['cp', '.env', 'environment.yml']
   id: 'setenv'
 - name: 'gcr.io/cloud-builders/npm'
   args:
   - serverless
   - deploy
images: ['gcr.io/${PROJECT_ID}/serverless-image']
